#ifndef INC_CPPVK_CONFIG_H_
#define INC_CPPVK_CONFIG_H_
/**
@file cppvk_config.h
@author t-sakai
@date 2018/08/31 create
*/

namespace cppvk
{
#define CPPVK_MAX_PHYSICAL_DEVICES (4)
#define CPPVK_MAX_QUEUE_FAMILY_PROPERTIES (8)
#define CPPVK_MAX_LAYERS (8)
#define CPPVK_MAX_INSTANCE_EXTENSION_PROPERTIES (32)
#define CPPVK_MAX_DEVICE_EXTENSION_PROPERTIES (64)

#define CPPVK_MAX_SURFACEFORMATS (32)
#define CPPVK_MAX_PRESENTMODES (4)

#define CPPVK_MAX_SWAPCHAINMIN (2)
#define CPPVK_MAX_SWAPCHAINMAX (4)
}
#endif //INC_CPPVK_CONFIG_H_
